/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package balancegeneral;

/**
 *
 * @author JAVIER
 */
public class BalanceG extends javax.swing.JFrame {

    /**
     * Creates new form BalanceG
     */
    public BalanceG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Bancotxt = new javax.swing.JTextField();
        SumaActivoC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Clientetxt = new javax.swing.JTextField();
        Almacenestxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Cajastxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TotalActivo = new javax.swing.JTextField();
        Edificios = new javax.swing.JTextField();
        Equipo = new javax.swing.JTextField();
        Inmuebles = new javax.swing.JTextField();
        TotalActivoFijo1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Calcular = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Proveedorestxt = new javax.swing.JTextField();
        Documentostxt = new javax.swing.JTextField();
        Acreedorestxt = new javax.swing.JTextField();
        Impuestostxt = new javax.swing.JTextField();
        TotalPasivoC = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        TotalPasivoFijo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        AcreHipo1 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Docporpagar1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        TotalCC = new javax.swing.JTextField();
        CapitalSocial = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        UtilidadesRetenidas1 = new javax.swing.JTextField();
        TOTALPC = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Utilidades retenidas");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 140, 20));

        jLabel4.setText("Clientes");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 100, 20));

        jLabel5.setText("Almacenes");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 70, 20));

        jLabel7.setText("Bancos");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 90, 20));

        jLabel8.setText("Edificios");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 50, 20));

        jLabel9.setText("Equipos");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 80, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1040, 20));

        jLabel10.setText("ACTIVO CIRCULANTE ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 300, 40));

        jLabel11.setText("Inmuebles");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 100, 20));

        jLabel12.setText("Proveedores");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 70, 20));

        jLabel13.setText("Documentos por pagar");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 130, 20));

        jLabel14.setText("Acreadores diversos");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 130, 20));

        jLabel15.setText("Impuestos por pagar");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 130, -1));

        jLabel16.setText("Cajas");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 70, 20));

        jLabel17.setText("Total Activo Circulante");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 140, 20));

        jLabel18.setText("Total Activo Fijo");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 140, 20));

        jLabel19.setText("PASIVO CIRCULANTE");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 240, 40));

        jLabel20.setText("Total Capital Contable");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 630, 140, 20));

        jLabel21.setText("Total Pasivo Circulante");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 140, 20));

        Bancotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BancotxtActionPerformed(evt);
            }
        });
        jPanel2.add(Bancotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 90, -1));

        SumaActivoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaActivoCActionPerformed(evt);
            }
        });
        jPanel2.add(SumaActivoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 90, -1));

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));
        jPanel2.add(Clientetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 90, -1));
        jPanel2.add(Almacenestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 90, -1));

        jLabel3.setText("TOTAL PASIVO+ CAPITAL CONTABLE");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 660, 200, 40));

        jLabel23.setText("CAPITAL CONTABLE");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 120, 40));
        jPanel2.add(Cajastxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 90, -1));

        jLabel6.setText("ACTIVO FIJO");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 120, 40));

        jLabel24.setText("TOTAL ACTIVO");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 120, 40));

        jLabel25.setText("PASIVO FIJO");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 120, 40));

        jLabel26.setText("Acreedores ");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 140, 30));

        jLabel27.setText("Capital social");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 140, 20));

        TotalActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActivoActionPerformed(evt);
            }
        });
        jPanel2.add(TotalActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 670, 90, 30));

        Edificios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdificiosActionPerformed(evt);
            }
        });
        jPanel2.add(Edificios, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 90, 30));

        Equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipoActionPerformed(evt);
            }
        });
        jPanel2.add(Equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 90, 30));

        Inmuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InmueblesActionPerformed(evt);
            }
        });
        jPanel2.add(Inmuebles, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 90, 30));

        TotalActivoFijo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActivoFijo1ActionPerformed(evt);
            }
        });
        jPanel2.add(TotalActivoFijo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 90, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 140, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 140, 10));

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        jPanel2.add(Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, -1, -1));

        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 670, -1, -1));

        Proveedorestxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedorestxtActionPerformed(evt);
            }
        });
        jPanel2.add(Proveedorestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 90, 30));

        Documentostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentostxtActionPerformed(evt);
            }
        });
        jPanel2.add(Documentostxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 90, 30));

        Acreedorestxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcreedorestxtActionPerformed(evt);
            }
        });
        jPanel2.add(Acreedorestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 90, 30));

        Impuestostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImpuestostxtActionPerformed(evt);
            }
        });
        jPanel2.add(Impuestostxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 90, 30));

        TotalPasivoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPasivoCActionPerformed(evt);
            }
        });
        jPanel2.add(TotalPasivoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 90, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 140, 10));

        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, -1, -1));

        TotalPasivoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPasivoFijoActionPerformed(evt);
            }
        });
        jPanel2.add(TotalPasivoFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 90, 30));

        jLabel1.setText("Hipotecarios");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 80, 30));

        jLabel22.setText("Documentos por pagar");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, -1));

        jLabel28.setText("a largo plazo");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        AcreHipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcreHipo1ActionPerformed(evt);
            }
        });
        jPanel2.add(AcreHipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 90, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 140, 10));

        Docporpagar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Docporpagar1ActionPerformed(evt);
            }
        });
        jPanel2.add(Docporpagar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 90, 30));

        jButton4.setText("Calcular");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, -1, -1));

        TotalCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalCCActionPerformed(evt);
            }
        });
        jPanel2.add(TotalCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 90, 30));

        CapitalSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapitalSocialActionPerformed(evt);
            }
        });
        jPanel2.add(CapitalSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 90, 30));

        jButton5.setText("Calcular");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 620, -1, -1));

        jLabel29.setText("Total Pasivo Fijo");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 140, 20));

        UtilidadesRetenidas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UtilidadesRetenidas1ActionPerformed(evt);
            }
        });
        jPanel2.add(UtilidadesRetenidas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 90, 30));

        TOTALPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTALPCActionPerformed(evt);
            }
        });
        jPanel2.add(TOTALPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 670, 90, 30));

        jButton6.setText("Calcular");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 680, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Balance general a :");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 150, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Persona que autoriza:");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, 200, 20));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 260, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, 260, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Nombre de la empresa:");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 200, 20));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Nombre del contador:");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, 200, 20));
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 260, -1));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, 260, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 1170, 910));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BancotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BancotxtActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_BancotxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double salariobanco = new Double(Bancotxt.getText()); 
        Double salariocajas = new Double(Cajastxt.getText());
        Double salariocliente = new Double(Clientetxt.getText());
        Double salarioalmacen = new Double(Almacenestxt.getText());
        
        Double SumaActivoTotal=salariobanco+salariocajas+salariocliente+salarioalmacen;
        
        SumaActivoC.setText(""+(SumaActivoTotal)); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SumaActivoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaActivoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SumaActivoCActionPerformed

    private void TotalActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActivoActionPerformed
        Double salariobanco = new Double(Bancotxt.getText()); 
        Double salariocajas = new Double(Cajastxt.getText());
        Double salariocliente = new Double(Clientetxt.getText());
        Double salarioalmacen = new Double(Almacenestxt.getText());
        
        Double SumaActivoTotal=salariobanco+salariocajas+salariocliente+salarioalmacen;
        
        SumaActivoC.setText(""+(SumaActivoTotal)); 
        
        
    }//GEN-LAST:event_TotalActivoActionPerformed

    private void EdificiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdificiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdificiosActionPerformed

    private void EquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipoActionPerformed

    private void InmueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InmueblesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InmueblesActionPerformed

    private void TotalActivoFijo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActivoFijo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActivoFijo1ActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        Double Edificiosxd = new Double(Edificios.getText()); 
        Double Equiposxd = new Double(Equipo.getText());
        Double Inmueblesxd = new Double(Inmuebles.getText());
        
        Double SumaActivoTotal2 = Edificiosxd + Equiposxd + Inmueblesxd;
        
        TotalActivoFijo1.setText(""+(SumaActivoTotal2)); 
    }//GEN-LAST:event_CalcularActionPerformed

    private void ProveedorestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedorestxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProveedorestxtActionPerformed

    private void DocumentostxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentostxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocumentostxtActionPerformed

    private void AcreedorestxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcreedorestxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcreedorestxtActionPerformed

    private void ImpuestostxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImpuestostxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImpuestostxtActionPerformed

    private void TotalPasivoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPasivoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPasivoCActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Double prove = new Double(Proveedorestxt.getText()); 
        Double docum = new Double(Documentostxt.getText());
        Double acre = new Double(Acreedorestxt.getText());
        Double imp = new Double(Impuestostxt.getText());
        
        Double SumaPasivoC=prove+docum+acre+imp;
        
        TotalPasivoC.setText(""+(SumaPasivoC));
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TotalPasivoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPasivoFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPasivoFijoActionPerformed

    private void AcreHipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcreHipo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcreHipo1ActionPerformed

    private void Docporpagar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Docporpagar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Docporpagar1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        Double Acredores = new Double(AcreHipo1.getText()); 
        Double docporpagar = new Double(Docporpagar1.getText());
        
        Double SumaPasivoF = Acredores + docporpagar;
        
        TotalPasivoFijo.setText(""+(SumaPasivoF));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TotalCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalCCActionPerformed

    private void CapitalSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapitalSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CapitalSocialActionPerformed

    private void UtilidadesRetenidas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UtilidadesRetenidas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UtilidadesRetenidas1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Double Capital = new Double(CapitalSocial.getText()); 
        Double Utilidades = new Double(UtilidadesRetenidas1.getText());
        
        Double SumaCC = Capital + Utilidades;
        
        TotalCC.setText(""+(SumaCC));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TOTALPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTALPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TOTALPCActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Double prove = new Double(Proveedorestxt.getText()); 
        Double docum = new Double(Documentostxt.getText());
        Double acre = new Double(Acreedorestxt.getText());
        Double imp = new Double(Impuestostxt.getText());
        
        Double SumaPasivoC=prove+docum+acre+imp;
        
        Double Acredores = new Double(AcreHipo1.getText()); 
        Double docporpagar = new Double(Docporpagar1.getText());
        
        Double SumaPasivoF = Acredores + docporpagar;
        
        Double Capital = new Double(CapitalSocial.getText()); 
        Double Utilidades = new Double(UtilidadesRetenidas1.getText());
        
        Double SumaCC = Capital + Utilidades;
        
        Double totaltotal=SumaPasivoC+SumaPasivoF+SumaCC;
        TOTALPC.setText(""+(totaltotal));
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Double salariobanco = new Double(Bancotxt.getText()); 
        Double salariocajas = new Double(Cajastxt.getText());
        Double salariocliente = new Double(Clientetxt.getText());
        Double salarioalmacen = new Double(Almacenestxt.getText());
        
        Double SumaActivoTotal=salariobanco+salariocajas+salariocliente+salarioalmacen;
        
            
        Double Edificiosxd = new Double(Edificios.getText()); 
        Double Equiposxd = new Double(Equipo.getText());
        Double Inmueblesxd = new Double(Inmuebles.getText());
        
        Double SumaActivoTotal2 = Edificiosxd + Equiposxd + Inmueblesxd;
        
        Double TAA=SumaActivoTotal+SumaActivoTotal2;
        
      TotalActivo.setText(""+(TAA));
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BalanceG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AcreHipo1;
    private javax.swing.JTextField Acreedorestxt;
    private javax.swing.JTextField Almacenestxt;
    private javax.swing.JTextField Bancotxt;
    private javax.swing.JTextField Cajastxt;
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField CapitalSocial;
    private javax.swing.JTextField Clientetxt;
    private javax.swing.JTextField Docporpagar1;
    private javax.swing.JTextField Documentostxt;
    private javax.swing.JTextField Edificios;
    private javax.swing.JTextField Equipo;
    private javax.swing.JTextField Impuestostxt;
    private javax.swing.JTextField Inmuebles;
    private javax.swing.JTextField Proveedorestxt;
    private javax.swing.JTextField SumaActivoC;
    private javax.swing.JTextField TOTALPC;
    private javax.swing.JTextField TotalActivo;
    private javax.swing.JTextField TotalActivoFijo1;
    private javax.swing.JTextField TotalCC;
    private javax.swing.JTextField TotalPasivoC;
    private javax.swing.JTextField TotalPasivoFijo;
    private javax.swing.JTextField UtilidadesRetenidas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
